version: "3.9"

services:
    python:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./ :/workouttracker
        ports:
            - 8080:8080

