# Generated by Django 3.2.5 on 2022-05-06 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number_of_sets', models.CharField(max_length=2)),
                ('number_of_reps', models.CharField(max_length=2)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workout_app.workout')),
            ],
        ),
    ]
