# Generated by Django 3.2.5 on 2022-05-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0002_exercise_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exercises', to='workout_app.workout'),
        ),
    ]
